"""
Notebook Builder - Assemble cells into executable .ipynb format
"""

import nbformat
from nbformat.v4 import new_notebook, new_markdown_cell, new_code_cell
from typing import Dict, List
from code_generator import CodeGenerator


class NotebookBuilder:
    def __init__(self):
        self.nb_version = 4
    
    def build_eda_notebook(
        self,
        dataset_path: str,
        intent: Dict,
        code_generator: CodeGenerator
    ) -> nbformat.NotebookNode:
        """
        Build a complete EDA notebook based on intent
        """
        nb = new_notebook()
        
        # Add title and introduction
        nb.cells.append(self._create_title_cell(intent))
        nb.cells.append(self._create_setup_cell(dataset_path))
        
        # Add sections based on intent
        sections = intent.get("suggested_sections", [
            "data_overview",
            "missing_values",
            "statistical_summary",
            "distributions",
            "correlations"
        ])
        
        schema_info = intent.get("schema", {})
        
        for section in sections:
            # Add markdown header
            markdown = code_generator.generate_markdown(section)
            nb.cells.append(new_markdown_cell(markdown))
            
            # Add code cell
            additional_context = ""
            if section == "target_analysis" and intent.get("target_column"):
                additional_context = f"Target column: {intent['target_column']}"
            
            code = code_generator.generate_section_code(
                section,
                schema_info,
                additional_context
            )
            nb.cells.append(new_code_cell(code))
        
        # Add summary section
        nb.cells.append(self._create_summary_cell(intent))
        
        return nb
    
    def _create_title_cell(self, intent: Dict) -> nbformat.NotebookNode:
        """Create notebook title and metadata"""
        title = f"""# 🤖 Agentic Notebook: Exploratory Data Analysis

**Generated by:** Agentic Notebook Generator v1.0  
**Task Type:** {intent.get('task_type', 'EDA').upper()}  
**Analysis Goals:**
{chr(10).join(f"- {goal}" for goal in intent.get('analysis_goals', ['Exploratory Data Analysis']))}

---
"""
        return new_markdown_cell(title)
    
    def _create_setup_cell(self, dataset_path: str) -> nbformat.NotebookNode:
        """Create imports and data loading cell"""
        code = f"""# Import required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

# Configure visualization settings
warnings.filterwarnings('ignore')
plt.style.use('seaborn-v0_8-darkgrid')
sns.set_palette("husl")
%matplotlib inline

# Set display options
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)

# Load dataset
df = pd.read_csv(r'{dataset_path}')

print("✅ Dataset loaded successfully!")
print(f"Shape: {{df.shape[0]}} rows × {{df.shape[1]}} columns")
"""
        return new_code_cell(code)
    
    def _create_summary_cell(self, intent: Dict) -> nbformat.NotebookNode:
        """Create summary and key findings cell"""
        markdown = """## 📝 Summary & Key Findings

This notebook performed comprehensive exploratory data analysis on the dataset. Key insights include:

1. **Data Quality:** Examined missing values, outliers, and data distributions
2. **Statistical Characteristics:** Analyzed central tendencies, spread, and correlations
3. **Variable Relationships:** Identified important correlations and patterns

**Next Steps:**
- Based on the EDA findings, consider appropriate preprocessing strategies
- Select relevant features for modeling (if applicable)
- Address data quality issues identified during analysis

---

*Generated automatically by Agentic Notebook Generator - Phase 1 MVP*
"""
        return new_markdown_cell(markdown)
